import './src/styles/fonts/montserrat900.css'
import './src/styles/fonts/montserrat800.css'
import './src/styles/fonts/montserrat700.css'
import '@fontsource/nothing-you-could-do'
import '@fontsource/raleway'
