import './src/styles/fonts/montserrat900.css'
import './src/styles/fonts/montserrat800.css'
import './src/styles/fonts/montserrat700.css'
import './src/styles/fonts/raleway600.css'
import './src/styles/fonts/raleway500.css'
import './src/styles/fonts/raleway400.css'
import '@fontsource/nothing-you-could-do'
